# Problem set 4: Descriptive economics I

**Table of contents**<a id='toc0_'></a>    
- 1. [Basic pandas](#toc1_)    
  - 1.1. [Dataframe](#toc1_1_)    
  - 1.2. [New variable](#toc1_2_)    
  - 1.3. [Indexing](#toc1_3_)    
  - 1.4. [Changing variables](#toc1_4_)    
  - 1.5. [Dropping observations and columns](#toc1_5_)    
  - 1.6. [Renaming](#toc1_6_)    
  - 1.7. [Income distribution](#toc1_7_)    
- 2. [Inflation](#toc2_)    
  - 2.1. [Basics](#toc2_1_)    
  - 2.2. [Instantanous inflation](#toc2_2_)    
  - 2.3. [Core inflation](#toc2_3_)    
  - 2.4. [CPI vs HICP](#toc2_4_)    
  - 2.5. [International comparison](#toc2_5_)    

<!-- vscode-jupyter-toc-config
	numbering=true
	anchor=true
	flat=false
	minLevel=2
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [1]:
import numpy as np
import pandas as pd
from IPython.display import display

import matplotlib.pyplot as plt
plt.rcParams.update({'axes.grid':True,'grid.color':'black','grid.alpha':'0.25','grid.linestyle':'--'})
plt.rcParams.update({'font.size': 14})

from dstapi import DstApi

## 1. <a id='toc1_'></a>[Basic pandas](#toc0_)

### 1.1. <a id='toc1_1_'></a>[Dataframe](#toc0_)

Modify the code below such that *income* and *consumption* are variables in the *df* DataFrame.

In [2]:
np.random.seed(1999)
 
N = 100
mydata = {}
mydata['id'] = range(N)
income = np.exp(np.random.normal(size=N))
consumption = np.sqrt(income)

df = pd.DataFrame(mydata)
df.head()

   id
0   0
1   1
2   2
3   3
4   4

In [3]:
display(df)

    id
0    0
1    1
2    2
3    3
4    4
..  ..
95  95
96  96
97  97
98  98
99  99

[100 rows x 1 columns]

### 1.2. <a id='toc1_2_'></a>[New variable](#toc0_)

Create a new variable *ratio* which is the ratio of consumption to income.

In [4]:
# write your code here
df.head()

   id
0   0
1   1
2   2
3   3
4   4

### 1.3. <a id='toc1_3_'></a>[Indexing](#toc0_)

**Question a:** Select everybody: with an income above 1.

In [5]:
# write your code here
df.head()

   id
0   0
1   1
2   2
3   3
4   4

**Question b:** Select everybody with an income *above* 1 and a ratio *above* 0.7.

In [6]:
# write your code here
df.head()

   id
0   0
1   1
2   2
3   3
4   4

### 1.4. <a id='toc1_4_'></a>[Changing variables](#toc0_)

**Question a:** Set consumption equal to 0.5 if income is less than 0.5.

In [7]:
# write your code here
# df['consumption'].mean() # <- compare with answer

**Question b:** Set consumption equal to income if income is less than 0.5.

In [8]:
# write your code here
# df['consumption'].mean() # <- compare with answer

### 1.5. <a id='toc1_5_'></a>[Dropping observations and columns](#toc0_)

Drop the *ratio* variable and all rows with an income above 1.5. After this, also drop the first 5 rows.

In [9]:
print(f'before: {df.shape[0]} observations, {df.shape[1]} variables')
# write your code here
print(f'after: {df.shape[0]} observations, {df.shape[1]} variables')

before: 100 observations, 1 variables
after: 100 observations, 1 variables

### 1.6. <a id='toc1_6_'></a>[Renaming](#toc0_)

Rename *consumption* to *cons* and *income* to *inc*.

In [10]:
# write your code
df.head()

   id
0   0
1   1
2   2
3   3
4   4

In [11]:
N = 100
mydata = {}
mydata['id'] = range(N)
mydata['income'] = np.exp(np.random.normal(size=N))
mydata['consumption'] = np.sqrt(mydata['income'])

df_true = pd.DataFrame(mydata)

df_true = df_true.rename(columns={'income':'inc','consumption':'con'})
df_true.head()

   id       inc       con
0   0  0.599145  0.774044
1   1  0.469167  0.684957
2   2  1.435292  1.198037
3   3  2.504716  1.582629
4   4  0.156667  0.395811

### 1.7. <a id='toc1_7_'></a>[Income distribution](#toc0_)

Compute the share of income for each decile of the income distribution using the code below as a starting point.

In [12]:
# deciles = df.quantile(?)
# df[?] = pd.cut(?,labels=?)
# income_shares df.groupby(?)[?].? / ?
# display(income_shares)

## 2. <a id='toc2_'></a>[Inflation](#toc0_)

### 2.1. <a id='toc2_1_'></a>[Basics](#toc0_)

Using table `PRIS113` from Denmark Statistics produce figures
with, respectively,

1. The consumer price index (CPI), $P_{t}$, indexed to $100$ on average
in $2020$
1. The month-to-month inflation rate, $\pi_{t}=P_{t}/P_{t-1}-1$
1. The 12-month inflation rate, $\pi^{12}_{t}=P_{t}/P_{t-12}-1$

When did the post-pandemic inflation surge end in Denmark? 

**Hint I**: You can use the `pandas` method`.pct_change`}.

**Hint II**: You can use the function `Y = pd.to_datetime(X,format='%YM%m')`
to create a date-variable, and then e.g. get the year as `Y.dt.year`

In [13]:
# write your code here

### 2.2. <a id='toc2_2_'></a>[Instantanous inflation](#toc0_)

The **instantaneous inflation rate** is defined as

$$
\begin{aligned}
\pi^{12,\alpha}_{t} &= \left(\prod_{k=0}^{11}\left(1+\pi_{t-k}\right)^{\kappa\left(k,\alpha\right)}\right)-1\\
\kappa\left(k,\alpha\right) &= \frac{\left(12-k\right)^{\alpha}}{\sum\left(12-k\right)^{\alpha}}12
\end{aligned}
$$

When $\alpha=0$ this is just the 12-month inflation rate. For higher $\alpha$ more weight is placed on inflation in the recent months.

1. Plot $\kappa(k,\alpha)$ for $k\in\{0,1,2,\dots,11\}$ and $\alpha\in\{0,1,2,3\}$
2. Compute $\pi^{12,\alpha}_{t}$ for $\alpha\in\{0,1,2,3\}$ (e.g. using the `.rolling(12).apply` method)
3. Plot $\pi^{12,\alpha}_{t}$ for $\alpha\in\{0,1,2,3\}$ since 2019

Can this be used to say something new about when the post-pandemic inflation surge ended in Denmark compared to your analysis above?

In [14]:
a_vec = np.array([0.0,1.0,2.0,3.0])
Na = a_vec.size
weights = np.zeros((Na,12))
for i_a in range(Na):
    weights[i_a] = (12-np.flip(np.arange(12)))**a_vec[i_a]
    weights[i_a] = weights[i_a]/np.sum(weights[i_a])*12

In [15]:
# write your code here

# to be used: .rolling(12).apply(lambda x: (np.prod((1+x/100)**(weights[i_a]))-1)*100)

### 2.3. <a id='toc2_3_'></a>[Core inflation](#toc0_)

Using table `PRIS111` from Denmark Statistics produce a
figure with 12-month inflation rates since 2019 for the following
series:

1. `VAREGR = 000000`: Consumer price index, total
1. `VAREGR = 151000`: ... excl. energy
1. `VAREGR = 141000`: ... excl. energy and unprocessed food
(core inflation).

What does this tell us about the most likely drivers of the post-pandemic
inflation surge in Denmark?

In [16]:
# write your code here

### 2.4. <a id='toc2_4_'></a>[CPI vs HICP](#toc0_)

Compare the CPI from Denmark Statistics with the Harmonized Index
for Consumer Prices (HICP) from FRED code `CP0000DKM086NEST`
(All Items). Are the two indexes comparable?

In [17]:
# write your code here

### 2.5. <a id='toc2_5_'></a>[International comparison](#toc0_)

Using FRED do the following for Denmark, Austria, the Euro Area and
the United States since 2019:

1. Compare HICP (All Items) across countries
1. Compute and compare the 12-month HICP inflation rate across countries

Summarize the cross-country differences in the path of inflation since
2019.

In [18]:
# write your code here