# Problem set 5: Descriptive economics II

**Table of contents**<a id='toc0_'></a>    
- 1. [National account identity](#toc1_)    
  - 1.1. [Download](#toc1_1_)    
  - 1.2. [Merge](#toc1_2_)    
  - 1.3. [Split-apply-combine-plot](#toc1_3_)    
- 2. [Disaggregated inflation in Denmark](#toc2_)    

<!-- vscode-jupyter-toc-config
	numbering=true
	anchor=true
	flat=false
	minLevel=2
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [1]:
import numpy as np
import pandas as pd
from IPython.display import display

import matplotlib.pyplot as plt
plt.rcParams.update({'axes.grid':True,'grid.color':'black','grid.alpha':'0.25','grid.linestyle':'--'})
plt.rcParams.update({'font.size': 14})

from dstapi import DstApi

## 1. <a id='toc1_'></a>[National account identity](#toc0_)

### 1.1. <a id='toc1_1_'></a>[Download](#toc0_)

Consider the following dictionary definitions:

In [2]:
columns_dict = {}
columns_dict['TRANSAKT'] = 'variable'
columns_dict['PRISENHED'] = 'unit'
columns_dict['TID'] = 'year'
columns_dict['INDHOLD'] = 'value'

var_dict = {} # var is for variable
var_dict['P.1 Output'] = 'Y'
var_dict['P.3 Final consumption expenditure'] = 'C'
var_dict['P.3 Government consumption expenditure'] = 'G'
var_dict['P.5 Gross capital formation'] = 'I'
var_dict['P.6 Export of goods and services'] = 'X'
var_dict['P.7 Import of goods and services'] = 'M'

unit_dict = {}
unit_dict['2020-prices, chained values'] = 'real'
unit_dict['Current prices'] = 'nominal'

**Step 1:** Download all of table `nah1`.

In [3]:
# hint, nah1_api = DstApi('?') 
# hint, params = nah1_api._define_base_params(language='en')
# display(params)
# nah1 = nah1_api.get_data(?)

**Step 2:** Rename the columns using `columns_dict` and replace data using `var_dict` and `unit_dict`.

In [4]:
# hint, nah1_true = nah1_true.rename(?)

# for key,value in var_dict.items():
#   nah1.variable.replace(?)

#for key,value in unit_dict.items():
#   nah1.unit.replace(?)

**Step 3:** Only keep rows where the variable is in `[Y, C, G, I, X, M]`. Afterwards convert the `value` column to a float.

In [5]:
# write you code here
# nah1.value = nah1.value.astype('float')

**Step 4:** Discuss what the following summary statistics show.

In [6]:
# nah1.groupby(['variable','unit']).describe()

**Step 5:** Sort the dataset by year

In [7]:
# nah1 = nah1.sort_values(by='?')
# nah1.head()

### 1.2. <a id='toc1_2_'></a>[Merge](#toc0_)

Load population data from Denmark Statistics:

In [8]:
BEFOLK1_api = DstApi('BEFOLK1')
params = BEFOLK1_api._define_base_params(language='en')
display(params)

{'table': 'befolk1',
 'format': 'BULK',
 'lang': 'en',
 'variables': [{'code': 'KØN', 'values': ['*']},
  {'code': 'ALDER', 'values': ['*']},
  {'code': 'CIVILSTAND', 'values': ['*']},
  {'code': 'Tid', 'values': ['*']}]}

In [9]:
for code in ['KØN','CIVILSTAND']:
    print(code)
    display(BEFOLK1_api.variable_levels(code,language='en'))
    print('')

KØN

    id     text
0  TOT    I alt
1    1     Mænd
2    2  Kvinder

CIVILSTAND

    id            text
0  TOT           I alt
1    U           Ugift
2    G  Gift/separeret
3    E   Enke/enkemand
4    F        Fraskilt

In [10]:
params['variables'][0]['values'] = ['TOT'] 
params['variables'][2]['values'] = ['TOT'] 
BEFOLK1 = BEFOLK1_api.get_data(params=params)
display(BEFOLK1.head())

     KØN       ALDER CIVILSTAND   TID  INDHOLD
0  Total  Age, total      Total  1993  5180614
1  Total     0 years      Total  1993    67651
2  Total      1 year      Total  1993    64656
3  Total    10 years      Total  1993    54088
4  Total    11 years      Total  1993    54404

In [11]:
BEFOLK1 = BEFOLK1.rename(columns={'TID':'year','INDHOLD':'population'})
BEFOLK1 = BEFOLK1.drop(columns=['KØN','CIVILSTAND'])
pop = BEFOLK1[BEFOLK1.ALDER == 'Age, total'].drop(columns=['ALDER'])
pop.head()

     year  population
0    1993     5180614
101  2001     5349212
202  1999     5313577
303  2018     5781190
404  1972     4975653

**Question a:** Merge the population and the national account data, so there is a new column called `population`. Use the **merge function**.

In [12]:
# hint, merged = pd.merge(?,?,how='?',on=[?])
# merged_true.tail(10)

**Question b:** Merge the population on again, so there is a new column called `population_alt`. Use the **join method**.

In [13]:
# pop_with_index = pop.set_index(?)
# pop_with_index = pop_with_index.rename(columns={'population':'population_alt'})
# merged_with_index = merged.set_index(?)
# merged_alt = merged_with_index.join(?)
# merged_alt.tail(10)

**Question c:** Plot GDP per capita and GDP per working-age (18-65) using the code below as a starting point.

In [14]:
# ages = ?

# working_pop = BEFOLK1[BEFOLK1.ALDER.isin(?)].groupby('year').?
# working_pop = working_pop.drop(columns=['ALDER'])
# working_pop = working_pop.rename(columns={'population':'working_population'})

# merged = pd.merge(nah1, working_pop, how='left', on=['year'])
# merged = pd.merge(merged, pop, how='left', on=['year'])

### 1.3. <a id='toc1_3_'></a>[Split-apply-combine-plot](#toc0_)

Ensure the following code for a **split-apply-combine-plot** can run.

In [15]:
# # a. split
# nah1_true_grouped = nah1_true.groupby(['variable','unit'])
# nah1_true_grouped_first = nah1_true_grouped.value.first()
# nah1_true_grouped_first.name = 'first'

# # b. apply
# nah1_true = nah1_true.set_index(['variable','unit','year'])
# nah1_true = nah1_true.join(nah1_true_grouped_first,how='left',on=['variable','unit'])
# nah1_true = nah1_true.reset_index()

# # c. combine
# nah1_true['indexed'] = nah1_true['value']/nah1_true['first']

# # d. plot
# def plot(df,variable='indexed'):
#     df_indexed = df.set_index('year')
#     I = df_indexed.unit == 'real'
#     df_indexed[I].groupby(['variable'])[variable].plot(legend=True);
    
# plot(nah1_true)

**Question:** Implement the same split-apply-combine as above using `transform`.

In [16]:
def first(x): # select the first element in a series
    return x.iloc[0]

# nah1_alt = nah1.copy()
# grouped = nah1_alt.groupby(?)
#nah1_alt[?] = ?.transform(lambda x: ?)
#nah1_alt.head()

In [17]:
# plot(nah1_alt,variable='index_transform')

## 2. <a id='toc2_'></a>[Disaggregated inflation in Denmark](#toc0_)

**Question 1.** Using table `PRIS111` from Denmark Statistics create a list of all 4-digit product categories (e.g. `01.1.1.1 Rice`)

In [22]:
# hint: start from the code below to get the levels of the variable VAREGR in PRIS111
# levels = DstApi('PRIS111').variable_levels('VAREGR',language='en' )
# for row in levels.itertuples(): print(row.id,row.text)

# write your code here

**Question 2:** Compute the 12-month inflation rate for the 4-digit product categories
using `.groupby` and compute the 25th, 50th and 75th percentile 
for each month in the data using `.agg`. Plot and describe
what you see.

In [19]:
# write your code here

**Question 3:** Plot the histogram of the percent change in prices for 4-digit product
categories from August 2020 to August 2025. Describe what you see.

In [20]:
# write your code here

**Question 4:** Illustrate the top 10 and bottom 10 product categories.

In [21]:
# write your code here